const userDetailResponseSerializer = (user) => ({
    id: user.id,
    username: user.username,
    referenceNumber: user.referenceNumber,
    email: user.email,
    phone: user.phone,
    name: user.name,
    surname: user.surname,
    photo: user.photo,
    gender: user.gender,
    userRoleId: user.userRoleId,
    isStaff: user.isStaff,
    isAdmin: user.isAdmin,
    isOwner: user.isOwner,
    isActive: user.isActive,
    createdBy: user.createdBy,
    updatedBy: user.updatedBy,
    userRole: user.userRole,
    categoriesCreated: user.categoriesCreated,
    categoriesUpdated: user.categoriesUpdated,
    eventsCreated: user.eventsCreated,
    eventsUpdated: user.eventsUpdated,
    eventsApprovedBy: user.eventsApprovedBy,
    eventsOwner: user.eventsOwner,
    workshopsCreatedBy: user.workshopsCreatedBy,
    workshopsUpdatedBy: user.workshopsUpdatedBy,
    workshopsApprovedBy: user.workshopsApprovedBy,
    workshopsOwner: user.workshopsOwner,
    participantsCreated: user.participantsCreated,
    participantsUpdated: user.participantsUpdated,
    participantsApprovedBy: user.participantsApprovedBy,
    participantsOwner: user.participantsOwner,
    messagesCreated: user.messagesCreated,
    messagesUpdated: user.messagesUpdated,
    permissionsCreated: user.permissionsCreated,
    permissionsUpdated: user.permissionsUpdated,
    userRolesCreated: user.userRolesCreated,
    userRolesUpdated: user.userRolesUpdated,
    participantRolesCreated: user.participantRolesCreated,
    participantRolesUpdated: user.participantRolesUpdated,
    
    eventParticipantsApprovedBy: user.eventParticipantsApprovedBy,
    eventParticipantsOwner: user.eventParticipantsOwner,
    eventParticipantsCreated: user.eventParticipantsCreated,
    eventParticipantsUpdated: user.eventParticipantsUpdated,
    EventParticipantRolesCreated: user.EventParticipantRolesCreated,
    EventParticipantRolesUpdated: user.EventParticipantRolesUpdated,
  });
  
  module.exports = userDetailResponseSerializer;